import { type Metadata } from "next";
import { SITE, SERVICES, PROCESS_STEPS, CONTACT } from "./constants";

export function constructMetadata(overrides?: Partial<Metadata>): Metadata {
  const title = `${SITE.name} | ${SITE.tagline}`;

  return {
    title: {
      default: title,
      template: `%s | ${SITE.name}`,
    },
    description: SITE.description,
    metadataBase: new URL(SITE.url),
    alternates: {
      canonical: "/",
    },
    keywords: [
      "AI automation",
      "business automation",
      "AI voice receptionist",
      "chatbot automation",
      "workflow automation",
      "n8n automation",
      "lead generation automation",
      "AI agents for business",
      "CRM automation",
      "dental clinic automation",
      "small business AI",
      "automation consultant",
      "Altaris",
    ],
    authors: [{ name: SITE.name, url: SITE.url }],
    creator: SITE.name,
    publisher: SITE.name,
    openGraph: {
      title,
      description: SITE.description,
      url: SITE.url,
      siteName: SITE.name,
      type: "website",
      locale: "en_US",
      // OG image is auto-generated by app/opengraph-image.tsx
    },
    twitter: {
      card: "summary_large_image",
      title,
      description: SITE.description,
      // Twitter image is auto-generated by app/opengraph-image.tsx
    },
    robots: {
      index: true,
      follow: true,
      googleBot: {
        index: true,
        follow: true,
        "max-video-preview": -1,
        "max-image-preview": "large",
        "max-snippet": -1,
      },
    },
    other: {
      "theme-color": "#0F172A",
      "color-scheme": "dark",
      "msapplication-TileColor": "#6C5CE7",
    },
    ...overrides,
  };
}

export function getJsonLd() {
  return {
    "@context": "https://schema.org",
    "@graph": [
      // Organization
      {
        "@type": "ProfessionalService",
        "@id": `${SITE.url}/#organization`,
        name: SITE.name,
        url: SITE.url,
        description: SITE.description,
        email: CONTACT.email,
        sameAs: [CONTACT.whatsapp],
        areaServed: "Worldwide",
        priceRange: "$$",
        serviceType: "AI Automation Consulting",
        knowsAbout: [
          "Artificial Intelligence",
          "Business Automation",
          "Workflow Automation",
          "AI Voice Agents",
          "Chatbot Development",
          "n8n",
          "CRM Automation",
        ],
      },

      // WebSite
      {
        "@type": "WebSite",
        "@id": `${SITE.url}/#website`,
        name: SITE.name,
        url: SITE.url,
        description: SITE.description,
        publisher: { "@id": `${SITE.url}/#organization` },
      },

      // WebPage
      {
        "@type": "WebPage",
        "@id": `${SITE.url}/#webpage`,
        url: SITE.url,
        name: `${SITE.name} | ${SITE.tagline}`,
        description: SITE.description,
        isPartOf: { "@id": `${SITE.url}/#website` },
        about: { "@id": `${SITE.url}/#organization` },
      },

      // Services offered
      ...SERVICES.map((service) => ({
        "@type": "Service",
        provider: { "@id": `${SITE.url}/#organization` },
        name: service.title,
        description: service.description,
      })),

      // HowTo (Process)
      {
        "@type": "HowTo",
        name: "How Altaris Builds Automation Systems",
        description:
          "A proven four-step process to design, build, and optimize your automation systems.",
        step: PROCESS_STEPS.map((step) => ({
          "@type": "HowToStep",
          position: step.step,
          name: step.title,
          text: step.description,
        })),
      },

      // FAQ
      {
        "@type": "FAQPage",
        mainEntity: [
          {
            "@type": "Question",
            name: "What is AI automation for business?",
            acceptedAnswer: {
              "@type": "Answer",
              text: "AI automation uses artificial intelligence agents and workflow tools to handle repetitive business tasks like answering calls, booking appointments, responding to messages, and managing leads — reducing manual work by up to 80%.",
            },
          },
          {
            "@type": "Question",
            name: "What businesses benefit from AI automation?",
            acceptedAnswer: {
              "@type": "Answer",
              text: "Small businesses, dental clinics, local service businesses, startups, and marketing agencies benefit most from AI automation systems that handle scheduling, customer communication, and lead management.",
            },
          },
          {
            "@type": "Question",
            name: "How long does it take to set up an automation system?",
            acceptedAnswer: {
              "@type": "Answer",
              text: "Most automation systems are designed, built, and deployed within 2-4 weeks depending on complexity. Our process includes an audit, architecture design, build & deploy, and ongoing optimization.",
            },
          },
        ],
      },

      // BreadcrumbList
      {
        "@type": "BreadcrumbList",
        itemListElement: [
          {
            "@type": "ListItem",
            position: 1,
            name: "Home",
            item: SITE.url,
          },
        ],
      },
    ],
  };
}
